{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl-0.4.1.jar",
          "url": "yamtl-0.4.1.jar",
          "size": 447246,
          "sha512": "461de9987887afa5bdd6a105ca4fed87998a0035401d67f8b47594fe12c0ba3f33a3da9625df7aa231b1f0e3e5c03630509f885dccc220f4a79c55fb24925dc5",
          "sha256": "1edbca8aa324891293c14945aefaf26ce068bad381879829cede99cbad9007dc",
          "sha1": "b8ef600fc27c1f89bb3f5b5b19bd548b6759e05d",
          "md5": "b9045136707d0c28184c64a9345fbb4e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "yamtl",
          "module": "untyped-models",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml",
          "version": {
            "requires": "8059"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl-0.4.1.jar",
          "url": "yamtl-0.4.1.jar",
          "size": 447246,
          "sha512": "461de9987887afa5bdd6a105ca4fed87998a0035401d67f8b47594fe12c0ba3f33a3da9625df7aa231b1f0e3e5c03630509f885dccc220f4a79c55fb24925dc5",
          "sha256": "1edbca8aa324891293c14945aefaf26ce068bad381879829cede99cbad9007dc",
          "sha1": "b8ef600fc27c1f89bb3f5b5b19bd548b6759e05d",
          "md5": "b9045136707d0c28184c64a9345fbb4e"
        }
      ]
    }
  ]
}
