{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "untyped-models",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "untyped-models-0.0.19.jar",
          "url": "untyped-models-0.0.19.jar",
          "size": 72660,
          "sha512": "7594372c8adac26e233ad079660320eed1aea5075757e7db7c8957812a6c78ac3603b3dd33b89246edda23db289126c0034715829dfe032df3c29354b3a04c2b",
          "sha256": "d3e6183483149f0a2c8b92138be6a6451e0cc6b51d687721e71ccc068a8ca7ee",
          "sha1": "19ee2360ea93617a66a4b7da50a0504657907471",
          "md5": "d705cd23965473366688a57231c7df19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.33.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.edit",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.core.runtime",
          "version": {
            "requires": "3.26.100"
          }
        }
      ],
      "files": [
        {
          "name": "untyped-models-0.0.19.jar",
          "url": "untyped-models-0.0.19.jar",
          "size": 72660,
          "sha512": "7594372c8adac26e233ad079660320eed1aea5075757e7db7c8957812a6c78ac3603b3dd33b89246edda23db289126c0034715829dfe032df3c29354b3a04c2b",
          "sha256": "d3e6183483149f0a2c8b92138be6a6451e0cc6b51d687721e71ccc068a8ca7ee",
          "sha1": "19ee2360ea93617a66a4b7da50a0504657907471",
          "md5": "d705cd23965473366688a57231c7df19"
        }
      ]
    }
  ]
}
