{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "0.4.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.35.jar",
          "url": "yamtl.flexible-models-0.4.35.jar",
          "size": 49567,
          "sha512": "ed084ef4a17ac46e3d3035eaca0cbc0ec1b78d774d400d4412acc884c60d53d47ea065f27cc3852d8b590b3cc6a5a544bc78dbc4ec3b88cc7e6d871cd659ca0c",
          "sha256": "322687710afa2c1fbfcd6d320fd6eb0ebec11040bb365be2193755606bf7d435",
          "sha1": "4096a202104cb30c9fac7efddfb9f5e259fc34c7",
          "md5": "6e2381f48988418035e227df45da4662"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.35.jar",
          "url": "yamtl.flexible-models-0.4.35.jar",
          "size": 49567,
          "sha512": "ed084ef4a17ac46e3d3035eaca0cbc0ec1b78d774d400d4412acc884c60d53d47ea065f27cc3852d8b590b3cc6a5a544bc78dbc4ec3b88cc7e6d871cd659ca0c",
          "sha256": "322687710afa2c1fbfcd6d320fd6eb0ebec11040bb365be2193755606bf7d435",
          "sha1": "4096a202104cb30c9fac7efddfb9f5e259fc34c7",
          "md5": "6e2381f48988418035e227df45da4662"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.35-all.jar",
          "url": "yamtl.flexible-models-0.4.35-all.jar",
          "size": 49567,
          "sha512": "67d8fb6512c94cd087763beb3be25b5cb491382c71abb504d449b5ed2a03649ab9fd7a2c4da9958b61e0fd6916f83673b3305e9516c8ac195563a88962fc5722",
          "sha256": "ceaede6c3bc49ce5c1c193f26691caaa94b46d1483b3de960f1a227a4dc4c192",
          "sha1": "6c366a4596d19d0f705317bde23628fc3db200a8",
          "md5": "e80beef4f47f5906c44143a6647f9f72"
        }
      ]
    }
  ]
}
