theme: jekyll-theme-minimal
title: YAMTL
description: Yet Another Model Transformation Language 
logo: ./images/yaml-icon.png
url: "https://yamtl.github.io" # the base hostname & protocol for your site
google_analytics: UA-78418237-2
