{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.openai",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.openai-1.1.5.jar",
          "url": "yamtl.openai-1.1.5.jar",
          "size": 53843,
          "sha512": "a1aac95bbd827bb30c874463106cad1ad396937c311fb2a0ed8a4eb947f759b245716dd13c1efbe931e666c0f19822ab73f05630d63bc1e83086bf55452f08f1",
          "sha256": "66793dc32dbdab11b2457b664430033126260ad4aaa45844bc3ffb93ca30ec9b",
          "sha1": "00c6c1dc1a8828fe3dd9fb15f23fae9b8fe1a0b5",
          "md5": "b8a4fad5f6763f18061ddfddeb8810ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.groovy",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "yamtl",
          "module": "emf-syncer.subtyping",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.openai-1.1.5.jar",
          "url": "yamtl.openai-1.1.5.jar",
          "size": 53843,
          "sha512": "a1aac95bbd827bb30c874463106cad1ad396937c311fb2a0ed8a4eb947f759b245716dd13c1efbe931e666c0f19822ab73f05630d63bc1e83086bf55452f08f1",
          "sha256": "66793dc32dbdab11b2457b664430033126260ad4aaa45844bc3ffb93ca30ec9b",
          "sha1": "00c6c1dc1a8828fe3dd9fb15f23fae9b8fe1a0b5",
          "md5": "b8a4fad5f6763f18061ddfddeb8810ed"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.openai-1.1.5-all.jar",
          "url": "yamtl.openai-1.1.5-all.jar",
          "size": 53843,
          "sha512": "a7c3c35711d0b3fa1fec896c183e9b7068966b290256078f22ba0b0373e3612034c2dcb2d196fe698b1893977a36653911ab4022f1551cb555534a23c207eea5",
          "sha256": "0399ac0649265be51bf2f3291f3b28e50a42e86026a41738d4f44cbdf61e43f1",
          "sha1": "72f4c763bf615622ea922f1b308bcf3ac746c03e",
          "md5": "0e930d3ee3ca1129628d6d7e1c4a5a2e"
        }
      ]
    }
  ]
}
