{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.openai",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.openai-1.1.6.jar",
          "url": "yamtl.openai-1.1.6.jar",
          "size": 70178,
          "sha512": "35489fa14b7495fa46f20fd1cf175d34d546bf01f585b4605c022650d7c9e5c76269573eb7ecc30f7228e03ff7a066d983088ec8bc2b1305bdbd1e19fd44dbd1",
          "sha256": "bc8f5c7aae61ae8db13230ec52f2912b8f942c79d8d169b58c73ea050788eeb5",
          "sha1": "be7ddaf49c49e9d3e89ca3912371537978a72091",
          "md5": "6aa730be9c7df1c96930d169bf56d954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.groovy",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "yamtl",
          "module": "emf-syncer.subtyping",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.openai-1.1.6.jar",
          "url": "yamtl.openai-1.1.6.jar",
          "size": 70178,
          "sha512": "35489fa14b7495fa46f20fd1cf175d34d546bf01f585b4605c022650d7c9e5c76269573eb7ecc30f7228e03ff7a066d983088ec8bc2b1305bdbd1e19fd44dbd1",
          "sha256": "bc8f5c7aae61ae8db13230ec52f2912b8f942c79d8d169b58c73ea050788eeb5",
          "sha1": "be7ddaf49c49e9d3e89ca3912371537978a72091",
          "md5": "6aa730be9c7df1c96930d169bf56d954"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.openai-1.1.6-all.jar",
          "url": "yamtl.openai-1.1.6-all.jar",
          "size": 70178,
          "sha512": "676c101b31544101c21835535dbbb0fad94c5cab161cb7e41794b95d8714a644ac70bc69eb99f6d5db5c9b911dea15e25de521229c2e2b7f4303321fe21af5b4",
          "sha256": "7768745a3e6c8585ea93bcd721fad2a1ada0ec1ff4e2b8ec95762ff2ceb1e3ed",
          "sha1": "1108ba104c754325dc6bbe040cda0a4118e1c0d7",
          "md5": "8bb7244b6745714c102443b20443c612"
        }
      ]
    }
  ]
}
