{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.0.jar",
          "url": "yamtl.flexible-models-1.0.0.jar",
          "size": 49567,
          "sha512": "bda2d3b166139a4cbe810eaf5c78332b90de12e50ca050e147e56a7ca445666ce87ee1d1f88b81dc9901b6bcec60f627d412c93c245d9d9b7887dd6fe28372f2",
          "sha256": "471860ebd40c859f9130962edeba1b005e767d5d77007b948c892d49d1c4bd46",
          "sha1": "53aa315f77284e0922514e8b20a14fc422b12b4e",
          "md5": "8ab9aec111bb3fa2295befa2e04505d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.0.jar",
          "url": "yamtl.flexible-models-1.0.0.jar",
          "size": 49567,
          "sha512": "bda2d3b166139a4cbe810eaf5c78332b90de12e50ca050e147e56a7ca445666ce87ee1d1f88b81dc9901b6bcec60f627d412c93c245d9d9b7887dd6fe28372f2",
          "sha256": "471860ebd40c859f9130962edeba1b005e767d5d77007b948c892d49d1c4bd46",
          "sha1": "53aa315f77284e0922514e8b20a14fc422b12b4e",
          "md5": "8ab9aec111bb3fa2295befa2e04505d9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.0-all.jar",
          "url": "yamtl.flexible-models-1.0.0-all.jar",
          "size": 49567,
          "sha512": "d16dc4a668a514d946acec4b5ac6d874873a4af234a7acbba252ede72d36e76ef273506c6ea509241fb7cf34b3aa9ee44df8329546a02d1c6bd93b5e820a02bb",
          "sha256": "2f721b378d227b19b9dce3f41fd5ac1c4cb1c2e8a7b573425506e5d3ed7b858a",
          "sha1": "6c705e1e97676b42b27e9da1e2db73ba36e8be63",
          "md5": "4157b646b458cfc48c42edb254b63b02"
        }
      ]
    }
  ]
}
