{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "0.4.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.33.jar",
          "url": "yamtl.groovy-0.4.33.jar",
          "size": 30901,
          "sha512": "727939ed6b60ddba569d3233fc66cce73d0c7d75ac5a374dae407b25865baaab36e3a1e807d4f12686c6ddb19ceedcb4e6514c687429985f288a4986c4bda61a",
          "sha256": "1cf47ad62daccbd2fd5e86b9af5ace642c2e2e6340d5f7eeafaad7161b6f5e28",
          "sha1": "5f201456d2cddf0bb29a93baf260d894d218c84f",
          "md5": "6877df36ebd0db595f5da3de66db0592"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "yamtl",
          "module": "untyped-models",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "0.4.33"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-0.4.33.jar",
          "url": "yamtl.groovy-0.4.33.jar",
          "size": 30901,
          "sha512": "727939ed6b60ddba569d3233fc66cce73d0c7d75ac5a374dae407b25865baaab36e3a1e807d4f12686c6ddb19ceedcb4e6514c687429985f288a4986c4bda61a",
          "sha256": "1cf47ad62daccbd2fd5e86b9af5ace642c2e2e6340d5f7eeafaad7161b6f5e28",
          "sha1": "5f201456d2cddf0bb29a93baf260d894d218c84f",
          "md5": "6877df36ebd0db595f5da3de66db0592"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.33-all.jar",
          "url": "yamtl.groovy-0.4.33-all.jar",
          "size": 4804642,
          "sha512": "a5a830bebc8f172b12f03074c421d90eae4423ea48c2d4c9ef2ebef4f7a570bcc0801c4778301e60867f736fa8e3b396be0b58f3cb67b7f798a8492d679b5766",
          "sha256": "e790483f26155e05ee50866bbf9a7b59af892c17b829dfb0b8eeebd135b5c249",
          "sha1": "55abc2e617c8dfa318980b36c7ee5b0175c48b2e",
          "md5": "430c1ac669dafb94e49addcff3401ad2"
        }
      ]
    }
  ]
}
