{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "untyped-models",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "untyped-models-0.0.25.jar",
          "url": "untyped-models-0.0.25.jar",
          "size": 49323,
          "sha512": "ecb11ee5deae6453d005b960afedc97f8c2e20e01b7d9280128b47304f06e3566fbaf8f0b9fad2d7b719647eb3bbb6723abb976d8e2c17567e2472479d8c1a58",
          "sha256": "fd7e05eb32031976ceba632c4687ec86e727a4164cfdcb09152bad3be04a589c",
          "sha1": "603676c58b06dd4c4c883cfc8f0b30a4e5aa8580",
          "md5": "60b189cd3620e721fa56f056805a6677"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.33.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.edit",
          "version": {
            "requires": "2.18.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "org.eclipse.platform",
          "module": "org.eclipse.core.runtime",
          "version": {
            "requires": "3.26.100"
          }
        }
      ],
      "files": [
        {
          "name": "untyped-models-0.0.25.jar",
          "url": "untyped-models-0.0.25.jar",
          "size": 49323,
          "sha512": "ecb11ee5deae6453d005b960afedc97f8c2e20e01b7d9280128b47304f06e3566fbaf8f0b9fad2d7b719647eb3bbb6723abb976d8e2c17567e2472479d8c1a58",
          "sha256": "fd7e05eb32031976ceba632c4687ec86e727a4164cfdcb09152bad3be04a589c",
          "sha1": "603676c58b06dd4c4c883cfc8f0b30a4e5aa8580",
          "md5": "60b189cd3620e721fa56f056805a6677"
        }
      ]
    }
  ]
}
