{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.0.8.jar",
          "url": "yamtl.groovy-1.0.8.jar",
          "size": 34756,
          "sha512": "fe1ee357ec4b42722c9a7906ac147d91a5e5cd6cdee0ba64c946b4e030fae28118182cd9872ab5a97083d1e0a41615a77d5689cbeaf10cde7758eead8d2910f3",
          "sha256": "db5bbbd0aa35995959ec2675afd374c85002bed4134b62bc2d4c43cf37dcfcb2",
          "sha1": "26779392ccffdda2c1d2e7ec23d81247128e166e",
          "md5": "7dba6e00eef2c7b7262390f159a5d7d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.0.8"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-1.0.8.jar",
          "url": "yamtl.groovy-1.0.8.jar",
          "size": 34756,
          "sha512": "fe1ee357ec4b42722c9a7906ac147d91a5e5cd6cdee0ba64c946b4e030fae28118182cd9872ab5a97083d1e0a41615a77d5689cbeaf10cde7758eead8d2910f3",
          "sha256": "db5bbbd0aa35995959ec2675afd374c85002bed4134b62bc2d4c43cf37dcfcb2",
          "sha1": "26779392ccffdda2c1d2e7ec23d81247128e166e",
          "md5": "7dba6e00eef2c7b7262390f159a5d7d0"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.0.8-all.jar",
          "url": "yamtl.groovy-1.0.8-all.jar",
          "size": 34756,
          "sha512": "cb7ddd78be1476ef3c255166f164f9a88e0980dd67adaa24ac596b0a847451bd37bfc7ce39b0028b461dd06639cb760e9332057d5b8f78be4a0b4d6e50c95982",
          "sha256": "7d4447e714e14fb06a6760877e50f94d59a6ef46e68903c0146949d2d3ba1ab9",
          "sha1": "8a69f4c32d920bb92c57f978265737f1c510df7b",
          "md5": "8529a9e0c6f293d1a68e0fe6625a8bd9"
        }
      ]
    }
  ]
}
