{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.openai",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.openai-1.0.10.jar",
          "url": "yamtl.openai-1.0.10.jar",
          "size": 53843,
          "sha512": "495930e812b79f35fbff5048be3a77a0ba07e9aa3ce937c9744c82d3b08192adec72f0dd99e061121d73e3d492abaa0aedd463a78a1c0b87944dae12b7ac1ff3",
          "sha256": "34aebf8fb5e73bb212733cd6e14bb562c80e01adff50e24ed4ecc6e10d1a2257",
          "sha1": "8ba9698a2a98d271338467116a26b67a34fb5f9b",
          "md5": "a6283e868b1550c66d914b5019d6213e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.groovy",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "yamtl",
          "module": "emf-syncer.subtyping",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.openai-1.0.10.jar",
          "url": "yamtl.openai-1.0.10.jar",
          "size": 53843,
          "sha512": "495930e812b79f35fbff5048be3a77a0ba07e9aa3ce937c9744c82d3b08192adec72f0dd99e061121d73e3d492abaa0aedd463a78a1c0b87944dae12b7ac1ff3",
          "sha256": "34aebf8fb5e73bb212733cd6e14bb562c80e01adff50e24ed4ecc6e10d1a2257",
          "sha1": "8ba9698a2a98d271338467116a26b67a34fb5f9b",
          "md5": "a6283e868b1550c66d914b5019d6213e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.openai-1.0.10-all.jar",
          "url": "yamtl.openai-1.0.10-all.jar",
          "size": 53843,
          "sha512": "94ecda0d7da2d1408fb2e7795c3f6582db0cccfb2a334d2a9f6cf46ac2fe05dea9f7d88e1915ca098e2d49616cc5244496974325232a213f0a3b51a5cf40e324",
          "sha256": "043bd6d446ec950e53ec2046997935f92ad785d22a31a34a98de4f1b96d807e1",
          "sha1": "910f3160f42191f33bd008c478d85ff7fcbfe8d1",
          "md5": "8cf26e0c518cc54b5d915eff1c004bfd"
        }
      ]
    }
  ]
}
