/* Generated By:JavaCC: Do not edit this line. EmfaticParserConstants.java */
package org.eclipse.emf.emfatic.core.lang.gen.parser;

public interface EmfaticParserConstants {

  int EOF = 0;
  int SINGLELINECOMMENT = 1;
  int WS = 2;
  int PACKAGEKW = 6;
  int CLASSKW = 7;
  int IMPORTKW = 8;
  int ABSTRACTKW = 9;
  int INTERFACEKW = 10;
  int EXTENDSKW = 11;
  int SUPERKW = 12;
  int ATTRKW = 13;
  int REFKW = 14;
  int VALKW = 15;
  int READONLYKW = 16;
  int VOLATILEKW = 17;
  int TRANSIENTKW = 18;
  int UNSETTABLEKW = 19;
  int DERIVEDKW = 20;
  int UNIQUEKW = 21;
  int ORDEREDKW = 22;
  int RESOLVEKW = 23;
  int IDKW = 24;
  int TRUEKW = 25;
  int FALSEKW = 26;
  int OPKW = 27;
  int VOIDKW = 28;
  int DATATYPEKW = 29;
  int ENUMKW = 30;
  int MAPENTRYKW = 31;
  int THROWSKW = 32;
  int DOUBLESLASH = 33;
  int DOUBLEQUOTE = 34;
  int SINGLEQUOTE = 35;
  int BACKSLASH = 36;
  int LCURLY = 37;
  int RCURLY = 38;
  int LSQUARE = 39;
  int RSQUARE = 40;
  int LPAREN = 41;
  int RPAREN = 42;
  int DOT = 43;
  int COMMA = 44;
  int COLON = 45;
  int SEMI = 46;
  int STAR = 47;
  int PLUS = 48;
  int MINUS = 49;
  int EQUALS = 50;
  int QMARK = 51;
  int BANG = 52;
  int DOLLAR = 53;
  int HASH = 54;
  int AT = 55;
  int DOT_DOT = 56;
  int MINUS_GT = 57;
  int GT_LT = 58;
  int LT_GT = 59;
  int AMP = 60;
  int LT = 61;
  int GT = 62;
  int STRING_LITERAL = 63;
  int CHAR_LITERAL = 64;
  int LETTERORUNDERSCORE = 65;
  int LETTERORUNDERSCOREORDIGIT = 66;
  int INT_LITERAL = 67;
  int DIGIT = 68;
  int ESC = 69;
  int DIGITDIGITDIGIT = 70;
  int ID = 71;

  int DEFAULT = 0;
  int WithinComment = 1;

  String[] tokenImage = {
    "<EOF>",
    "<SINGLELINECOMMENT>",
    "<WS>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
    "\"package\"",
    "\"class\"",
    "\"import\"",
    "\"abstract\"",
    "\"interface\"",
    "\"extends\"",
    "\"super\"",
    "\"attr\"",
    "\"ref\"",
    "\"val\"",
    "\"readonly\"",
    "\"volatile\"",
    "\"transient\"",
    "\"unsettable\"",
    "\"derived\"",
    "\"unique\"",
    "\"ordered\"",
    "\"resolve\"",
    "\"id\"",
    "\"true\"",
    "\"false\"",
    "\"op\"",
    "\"void\"",
    "\"datatype\"",
    "\"enum\"",
    "\"mapentry\"",
    "\"throws\"",
    "\"//\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\\\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"?\"",
    "\"!\"",
    "\"$\"",
    "\"#\"",
    "\"@\"",
    "\"..\"",
    "\"->\"",
    "\"><\"",
    "\"<>\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
    "<STRING_LITERAL>",
    "<CHAR_LITERAL>",
    "<LETTERORUNDERSCORE>",
    "<LETTERORUNDERSCOREORDIGIT>",
    "<INT_LITERAL>",
    "<DIGIT>",
    "<ESC>",
    "<DIGITDIGITDIGIT>",
    "<ID>",
  };

}
