/**
 * @generated by Gymnast from Emfatic.ast on 09.02.2007 13:03:05
 */

package org.eclipse.emf.emfatic.core.lang.gen.parser;

public class ExtToken extends Token {

	/**
	 * The start position of the token in the input stream.
	 */
	public int tokenOffset;

}
