{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.2.jar",
          "url": "yamtl.flexible-models-1.0.2.jar",
          "size": 49567,
          "sha512": "31c1302dddb42d8f242e3b1e9270cf408bb4e6714938e94910d95d93a0c5fcbe32a5c45df244c10ac8b4a73a1af12a3ca1a9994b52fa0de85fdaf2122d710dd8",
          "sha256": "a00634ae1412f102119deb06797b714c6464a9e143909d3d3b08e4ce1145fc7d",
          "sha1": "3f124bbe4ba9346f352a63d4750bf343dffc2020",
          "md5": "f90eca9d69f03b95a0905f4e1e5b5260"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.2.jar",
          "url": "yamtl.flexible-models-1.0.2.jar",
          "size": 49567,
          "sha512": "31c1302dddb42d8f242e3b1e9270cf408bb4e6714938e94910d95d93a0c5fcbe32a5c45df244c10ac8b4a73a1af12a3ca1a9994b52fa0de85fdaf2122d710dd8",
          "sha256": "a00634ae1412f102119deb06797b714c6464a9e143909d3d3b08e4ce1145fc7d",
          "sha1": "3f124bbe4ba9346f352a63d4750bf343dffc2020",
          "md5": "f90eca9d69f03b95a0905f4e1e5b5260"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.2-all.jar",
          "url": "yamtl.flexible-models-1.0.2-all.jar",
          "size": 49567,
          "sha512": "7b431cd01499756aac80cac7acf4ac7eae6280c4a7536c01e84925eea91836845b8213c520de0242601b736230160ce88af2670824495baec37530c9e2e48b84",
          "sha256": "027db1c1657f5f18d78d1f7f744185e4c31bbdc9ed28acf383b4ef5c30fd3965",
          "sha1": "f5abc94c7c357e6f5f066a1cccf53f7fcf66496f",
          "md5": "56764a40778de489d2ad867a38963faa"
        }
      ]
    }
  ]
}
