{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.1.jar",
          "url": "yamtl.flexible-models-1.0.1.jar",
          "size": 49567,
          "sha512": "0b0ee8a1b107c94785a14f9883baabf5722313c344cdb06746f23b7bc9d66b9aae6155400b020bffc528171f0b2e05aa5cd3c56f0d8ce3ccf8760d035850b370",
          "sha256": "b9a355969fdb821429f7549c3c3875eaab6acf6428411f1b7b4a90818131fc8a",
          "sha1": "e90488f6c78e1d9642d130f691419152485e7203",
          "md5": "b2b12f620b3d78edae1f2437d79ca76f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.1.jar",
          "url": "yamtl.flexible-models-1.0.1.jar",
          "size": 49567,
          "sha512": "0b0ee8a1b107c94785a14f9883baabf5722313c344cdb06746f23b7bc9d66b9aae6155400b020bffc528171f0b2e05aa5cd3c56f0d8ce3ccf8760d035850b370",
          "sha256": "b9a355969fdb821429f7549c3c3875eaab6acf6428411f1b7b4a90818131fc8a",
          "sha1": "e90488f6c78e1d9642d130f691419152485e7203",
          "md5": "b2b12f620b3d78edae1f2437d79ca76f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.1-all.jar",
          "url": "yamtl.flexible-models-1.0.1-all.jar",
          "size": 49567,
          "sha512": "125b6e4247bef39c63d1b5128454ad05c15dec055d5fa271914a558524ead9b39ed0ddae99958ea98368a5bc2dd55613b5df3e39961c7139d9a1a5cbfa5dff05",
          "sha256": "4151d32624d0fd69256a0da26e2c94015bf5f2a87b0d4ce2dd8db9fa784063cf",
          "sha1": "145b4da5bb69d08eaa27cf04a35ada2075fef157",
          "md5": "26f01c62e264d8df8f18f3522cb65836"
        }
      ]
    }
  ]
}
