{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "0.4.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.37.jar",
          "url": "yamtl.flexible-models-0.4.37.jar",
          "size": 49567,
          "sha512": "8bc84a14f61a718c665cc2a5d87b4347dc5ea1ae1584080da745edd45b19cf3d658e6cc6c178fc020936352471892c2103494ac82991a851b221038f9d7d9767",
          "sha256": "e3fc207d0ed320af57a776cd502133cbf1d674da6a1c1ba0d175bf9c989d9ecd",
          "sha1": "afc450f7eca764c783e331b62afd4cd2dcb8de17",
          "md5": "77608b9c712bd658b01a33d7a3c7e808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.37.jar",
          "url": "yamtl.flexible-models-0.4.37.jar",
          "size": 49567,
          "sha512": "8bc84a14f61a718c665cc2a5d87b4347dc5ea1ae1584080da745edd45b19cf3d658e6cc6c178fc020936352471892c2103494ac82991a851b221038f9d7d9767",
          "sha256": "e3fc207d0ed320af57a776cd502133cbf1d674da6a1c1ba0d175bf9c989d9ecd",
          "sha1": "afc450f7eca764c783e331b62afd4cd2dcb8de17",
          "md5": "77608b9c712bd658b01a33d7a3c7e808"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.37-all.jar",
          "url": "yamtl.flexible-models-0.4.37-all.jar",
          "size": 49567,
          "sha512": "368d608ad3057b0a443ad52eed15dc037f1998d9114920e402e306886e78d266a9e0419519d8607ccdc78a3f64791454507d7dea811f877d2a2e7d7da5267cda",
          "sha256": "c7b068b646e650bc65447ed83bc8c66a64143bfce00af5ec45bb5e36845ceffe",
          "sha1": "04df8b6f6fd470710413c9d66ab924ba20b0325e",
          "md5": "e8b2146fc7435024a4874e6504e155b9"
        }
      ]
    }
  ]
}
