{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl-0.2.6.jar",
          "url": "yamtl-0.2.6.jar",
          "size": 420097,
          "sha512": "4e29a766ed0f2c083051b1a7eddc866592005471a8ac549f4c19aeb0366e3d058f69988bb4d3ab86436873177a2bbbca6eef1e0d96ad2c903b6b4233311a39ce",
          "sha256": "a23f11d2f537c0d887e7b476a00324eacbd93c55dd7cbdb92aef3f7d64d0f784",
          "sha1": "6f559d3fd7db4530efadcc2c634d344a08bad6ba",
          "md5": "8af617bcb4744905e51c7528ebb35885"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.13.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml",
          "version": {
            "requires": "8059"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjrt",
          "version": {
            "requires": "1.9.9.1"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl-0.2.6.jar",
          "url": "yamtl-0.2.6.jar",
          "size": 420097,
          "sha512": "4e29a766ed0f2c083051b1a7eddc866592005471a8ac549f4c19aeb0366e3d058f69988bb4d3ab86436873177a2bbbca6eef1e0d96ad2c903b6b4233311a39ce",
          "sha256": "a23f11d2f537c0d887e7b476a00324eacbd93c55dd7cbdb92aef3f7d64d0f784",
          "sha1": "6f559d3fd7db4530efadcc2c634d344a08bad6ba",
          "md5": "8af617bcb4744905e51c7528ebb35885"
        }
      ]
    }
  ]
}
