{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.0.10.jar",
          "url": "yamtl.groovy-1.0.10.jar",
          "size": 34756,
          "sha512": "06036fa022b994e594a8d5c3946ae3465be782aba954a0ddf568af2bb028d15c0b734c48c3d38a851cfc6ca5ff2b0d775de99766aac7a9cf3ab94d7a74c9e843",
          "sha256": "62dc42da0ee18a5d37adf4d239c200316c87096c76af668278b233cbf2f52d0b",
          "sha1": "c76ccf710acf44266186fe52b695eae64e536728",
          "md5": "e2e9b33c60871cd9f0ffe4ad2b15c7b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.0.10"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-1.0.10.jar",
          "url": "yamtl.groovy-1.0.10.jar",
          "size": 34756,
          "sha512": "06036fa022b994e594a8d5c3946ae3465be782aba954a0ddf568af2bb028d15c0b734c48c3d38a851cfc6ca5ff2b0d775de99766aac7a9cf3ab94d7a74c9e843",
          "sha256": "62dc42da0ee18a5d37adf4d239c200316c87096c76af668278b233cbf2f52d0b",
          "sha1": "c76ccf710acf44266186fe52b695eae64e536728",
          "md5": "e2e9b33c60871cd9f0ffe4ad2b15c7b6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.0.10-all.jar",
          "url": "yamtl.groovy-1.0.10-all.jar",
          "size": 34756,
          "sha512": "aced0163c1f32b1148382d69ca0c0b038992d83b605ff9f995b530e708d1752751919bb0d28b43950667e2e7e490295b58b1c75d04eb3bd4bee7bc2170a00ec3",
          "sha256": "25d3b7a1cf3c2215d638e9d3ad064505fa458db1791c995757f570a8b5810eda",
          "sha1": "a0130778d97950d78b8e0a6e6d853fc9f00751c2",
          "md5": "6be70e55f770d73dfa0a2d25a9385a20"
        }
      ]
    }
  ]
}
