{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.1.8.jar",
          "url": "yamtl.groovy-1.1.8.jar",
          "size": 34756,
          "sha512": "653f5bf02964a4c249356f2a853bc4d63ca93917f61d55b2f3449a455d0c5e27ec29448943d7c52cfb8b988552a91f1c81c7dceea8d37f535bc76cc26002ac8b",
          "sha256": "1afeb72336376ea879117a2d254577e6c94f0bc5b78a6973b03da0e716e63913",
          "sha1": "361d452cf7c54576064bca402ad0db0981a42700",
          "md5": "a974d98c95846f006847121585fb9784"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-1.1.8.jar",
          "url": "yamtl.groovy-1.1.8.jar",
          "size": 34756,
          "sha512": "653f5bf02964a4c249356f2a853bc4d63ca93917f61d55b2f3449a455d0c5e27ec29448943d7c52cfb8b988552a91f1c81c7dceea8d37f535bc76cc26002ac8b",
          "sha256": "1afeb72336376ea879117a2d254577e6c94f0bc5b78a6973b03da0e716e63913",
          "sha1": "361d452cf7c54576064bca402ad0db0981a42700",
          "md5": "a974d98c95846f006847121585fb9784"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-1.1.8-all.jar",
          "url": "yamtl.groovy-1.1.8-all.jar",
          "size": 34756,
          "sha512": "855a4e434a97232c184fef43b7d803a467b7d09d26c3de4abd550c6f0548d3d3af55cb83e774042378ba5034af5eed0001b9f38793d8ce62863a23a2075343b7",
          "sha256": "5b2b0ad0396ad5fe58166bb9cea7fcb9cd7049e3cfdeb4056b694d0cd117174e",
          "sha1": "9474125c2383d9ee81decf90f75eccc6a7b4597c",
          "md5": "8843539fd9fdb478c68ed22ecb0c74a8"
        }
      ]
    }
  ]
}
