{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.8.jar",
          "url": "yamtl.flexible-models-1.0.8.jar",
          "size": 49567,
          "sha512": "d5c0db78bc7c24d415b3cd9e05e6718d7ded5aa4821fb3784e898aa7037a578f5d414047386a7f6369e6bcd4e6ca6de9eb30cdbe9fc4ceaa4728c1e3670f8dda",
          "sha256": "5bfbea2d5250667858b2471f14c223e7e121685e986fb87c65a5ba38972f122c",
          "sha1": "6e5b99dc38d621aae62a07ab74c4749fe2cc245b",
          "md5": "4b498745d44de9168ab04e1c85ad1a50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.8.jar",
          "url": "yamtl.flexible-models-1.0.8.jar",
          "size": 49567,
          "sha512": "d5c0db78bc7c24d415b3cd9e05e6718d7ded5aa4821fb3784e898aa7037a578f5d414047386a7f6369e6bcd4e6ca6de9eb30cdbe9fc4ceaa4728c1e3670f8dda",
          "sha256": "5bfbea2d5250667858b2471f14c223e7e121685e986fb87c65a5ba38972f122c",
          "sha1": "6e5b99dc38d621aae62a07ab74c4749fe2cc245b",
          "md5": "4b498745d44de9168ab04e1c85ad1a50"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.0.8-all.jar",
          "url": "yamtl.flexible-models-1.0.8-all.jar",
          "size": 49567,
          "sha512": "30a6424966c0784a415efbc5d364be7b04dc0ac1b609deebc760b16d5abb2180f86ab412e993fa425a164b076000beec2b00e541a249b71cfdaa9dcbeebf9080",
          "sha256": "a645dda13c10f00abc12af25e460b8f8cc15c2da3ae0341a12c2b86fb8743922",
          "sha1": "23cb6d89c9a2637ef5cdbb7df1b7944bbf86b507",
          "md5": "1eeb4fa7e92ac42fa7a29d3a48e8192d"
        }
      ]
    }
  ]
}
