{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "0.4.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.36.jar",
          "url": "yamtl.groovy-0.4.36.jar",
          "size": 33150,
          "sha512": "002c03efdd120b518d48ededa3762167ec9625d890b82f70836390a3c29303146b5b9a547a5de9d3ae6e8905b0017ebc1f8c5fc8c20bb0f3fafc0132501b647a",
          "sha256": "204344d8d7c8b33b5ee6aa1828cceaa345f913741680e4533d7cf96c36189312",
          "sha1": "cf9bf7f386161511fca7bf0256454b53916a3600",
          "md5": "45e00deee971e089fd2e9697919ffd76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "0.4.36"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "0.4.36"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-0.4.36.jar",
          "url": "yamtl.groovy-0.4.36.jar",
          "size": 33150,
          "sha512": "002c03efdd120b518d48ededa3762167ec9625d890b82f70836390a3c29303146b5b9a547a5de9d3ae6e8905b0017ebc1f8c5fc8c20bb0f3fafc0132501b647a",
          "sha256": "204344d8d7c8b33b5ee6aa1828cceaa345f913741680e4533d7cf96c36189312",
          "sha1": "cf9bf7f386161511fca7bf0256454b53916a3600",
          "md5": "45e00deee971e089fd2e9697919ffd76"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.36-all.jar",
          "url": "yamtl.groovy-0.4.36-all.jar",
          "size": 33150,
          "sha512": "36adb35372b4f3c15ce8b51b2e2e6e1c40d268c9ee9ae07e7d5aa5a05e89158aad18dd09965c1f8a8e394dd55c24bb3f9c299f012d86096c0b7e761bcc089647",
          "sha256": "a47a5689b6d55a8df2818d78d8070a898c053807f1bbe3ee093e2483e2464c59",
          "sha1": "62a6d1c9e5683d24eba5d64599f5ec2d1444ad58",
          "md5": "d0f6f8d67bcc4ac69af50902be0c2d0a"
        }
      ]
    }
  ]
}
