{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "0.4.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.35.jar",
          "url": "yamtl.groovy-0.4.35.jar",
          "size": 33150,
          "sha512": "a909bddf7268d1d73a3a9320fc4bd20ec0753b21a94b3be27a426d8efea07e1b0dd5e7cc557abbc4c945b7c365cd8ebfb05facf19822948377ac9238496ff686",
          "sha256": "7fc1ef04e94af3e5a6ad968c504ec9933d0a7083a87b5d72f1a6a30ad2cae7a8",
          "sha1": "5ba0a70fe719d4b7aadb21aad1b0e25503188d8f",
          "md5": "b028a0be026a852d0199f994e48b5f58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "0.4.35"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "0.4.35"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-0.4.35.jar",
          "url": "yamtl.groovy-0.4.35.jar",
          "size": 33150,
          "sha512": "a909bddf7268d1d73a3a9320fc4bd20ec0753b21a94b3be27a426d8efea07e1b0dd5e7cc557abbc4c945b7c365cd8ebfb05facf19822948377ac9238496ff686",
          "sha256": "7fc1ef04e94af3e5a6ad968c504ec9933d0a7083a87b5d72f1a6a30ad2cae7a8",
          "sha1": "5ba0a70fe719d4b7aadb21aad1b0e25503188d8f",
          "md5": "b028a0be026a852d0199f994e48b5f58"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.35-all.jar",
          "url": "yamtl.groovy-0.4.35-all.jar",
          "size": 33150,
          "sha512": "4f6bb9bea4e2204f238e646406b93ff8704a6924329b915616d8efc93ecd35e0da49dbc36ab768f4ca7cc0d707b886cd18679b04acd08d43e1bf6771508b9bcd",
          "sha256": "11e57d42a822ee99f1e934999b0c99cb88db6c0eebb4e47d5ef902336dc19786",
          "sha1": "8602bc19859cd6c01e8b86cb95a07e42f71a2d33",
          "md5": "d920226dd5bae968db7d0cba9e42450a"
        }
      ]
    }
  ]
}
