{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.groovy",
    "version": "0.4.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.35.jar",
          "url": "yamtl.groovy-0.4.35.jar",
          "size": 33150,
          "sha512": "f99ea25e4f440b4d64b12fff0cef702256e5c46d4171f16b5fb05af70bd6dc9ce28e04676632ec2b2349dfabffb9e6db4f0be4781c7fb44bebeb4eaeea234ac8",
          "sha256": "dc3d42b68d6b5fb10aa5d939a6e71aaf7723441c90abcbd55659da195e4f37f3",
          "sha1": "c3d1685887cc66c660dd4ac1f2863f5396846153",
          "md5": "3171d43e04043a03e914177e6b5e2953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "0.4.35"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "0.4.35"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.groovy-0.4.35.jar",
          "url": "yamtl.groovy-0.4.35.jar",
          "size": 33150,
          "sha512": "f99ea25e4f440b4d64b12fff0cef702256e5c46d4171f16b5fb05af70bd6dc9ce28e04676632ec2b2349dfabffb9e6db4f0be4781c7fb44bebeb4eaeea234ac8",
          "sha256": "dc3d42b68d6b5fb10aa5d939a6e71aaf7723441c90abcbd55659da195e4f37f3",
          "sha1": "c3d1685887cc66c660dd4ac1f2863f5396846153",
          "md5": "3171d43e04043a03e914177e6b5e2953"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.groovy-0.4.35-all.jar",
          "url": "yamtl.groovy-0.4.35-all.jar",
          "size": 33150,
          "sha512": "4ac32884bc88e1d23b138d33c179f0613d2eda0976bea37fbc9a1353ad1a6678ef5fdce711adbd6217d14666fe076679d49166e690124b5654935794d1965828",
          "sha256": "370a4255e29630f540cd2bb9aa0f055f9cadc1c8455536b21d3d54e134a61f10",
          "sha1": "5c6559e754e0d6cdc9b620b85cbddeb1fd74b582",
          "md5": "166cdc925742f53570aedfc630e95dd0"
        }
      ]
    }
  ]
}
