{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.openai",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.openai-1.0.9.jar",
          "url": "yamtl.openai-1.0.9.jar",
          "size": 53816,
          "sha512": "c699b94c8220afcbff7f4600444b5fb34e9635f2e6bfacea50768cb4903361a772ff288b129bdbdf4c1dfc0a439e3864caaaec32ad761b638e4d3c965a276931",
          "sha256": "bca0d9fa50b4f2023e7ff3ed0eedf8da6e8966bdbf2fb69a52178dbfe165a33d",
          "sha1": "1e7198682edb933ec739886aa64aa6f2b25cdb50",
          "md5": "f99dbb4f779be63ae3fac26b21bc4bdd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.groovy",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "yamtl",
          "module": "emf-syncer.subtyping",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.openai-1.0.9.jar",
          "url": "yamtl.openai-1.0.9.jar",
          "size": 53816,
          "sha512": "c699b94c8220afcbff7f4600444b5fb34e9635f2e6bfacea50768cb4903361a772ff288b129bdbdf4c1dfc0a439e3864caaaec32ad761b638e4d3c965a276931",
          "sha256": "bca0d9fa50b4f2023e7ff3ed0eedf8da6e8966bdbf2fb69a52178dbfe165a33d",
          "sha1": "1e7198682edb933ec739886aa64aa6f2b25cdb50",
          "md5": "f99dbb4f779be63ae3fac26b21bc4bdd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.openai-1.0.9-all.jar",
          "url": "yamtl.openai-1.0.9-all.jar",
          "size": 53816,
          "sha512": "eee3f7a4cef3c13b30e4ac1801b9d095085b9585cb9ec0bdee31b991bcf539dc930ad033fc1abfd0d0fa396df48b1b162326ddd0824714a3ac41117d4ad806e6",
          "sha256": "8a6da954fc44ee77676bed203cdefc8e2d2a1d536f6bfcdb1e781ac018c5e201",
          "sha1": "83c7a0fbac276f81f1c203315f010f66feec1ee4",
          "md5": "75b125eea4552593e1079cde878a802d"
        }
      ]
    }
  ]
}
