{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.emfatic",
    "version": "1.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.emfatic-1.1.8.jar",
          "url": "yamtl.emfatic-1.1.8.jar",
          "size": 70267,
          "sha512": "b536617e392dadc8539fdf25b81fd0130573dc9ec70ebc185a656bc9e3a308702a0196bc34d7ece11c5313c60df56d136dab2ab1637cefcdec74a4fd2c283e17",
          "sha256": "1259fc7421ce32adc70dfc28e42e66386a375c3d484371daea268a0eb677beae",
          "sha1": "80ad7d9d90beea8b5f0c16fe62a1671afdcff56d",
          "md5": "d8b31cb56214928af97f956821eb011b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.flexible-models",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "yamtl",
          "module": "yamtl.groovy",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "yamtl",
          "module": "emf-syncer.subtyping",
          "version": {
            "requires": "1.1.8"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.openai",
          "module": "openai-java",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.2"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.emfatic-1.1.8.jar",
          "url": "yamtl.emfatic-1.1.8.jar",
          "size": 70267,
          "sha512": "b536617e392dadc8539fdf25b81fd0130573dc9ec70ebc185a656bc9e3a308702a0196bc34d7ece11c5313c60df56d136dab2ab1637cefcdec74a4fd2c283e17",
          "sha256": "1259fc7421ce32adc70dfc28e42e66386a375c3d484371daea268a0eb677beae",
          "sha1": "80ad7d9d90beea8b5f0c16fe62a1671afdcff56d",
          "md5": "d8b31cb56214928af97f956821eb011b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.emfatic-1.1.8-all.jar",
          "url": "yamtl.emfatic-1.1.8-all.jar",
          "size": 70267,
          "sha512": "26b78f836836418e731d16e5e9ef510e1400e1f8b0f61bb399e679005482a202d98643e9c31f8154c726edfe1176fa91966de90230f27aeab053606d7505001c",
          "sha256": "7c824b26e3cc690ae685218b65f11f0fd51ad1c1c8b7fca3bb6f388d632fa066",
          "sha1": "3a700a54b17fcc49ff8e3c083e73f12686c597fe",
          "md5": "e787038932d1d515cf751db33b2609e6"
        }
      ]
    }
  ]
}
