{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "0.4.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.36.jar",
          "url": "yamtl.flexible-models-0.4.36.jar",
          "size": 49567,
          "sha512": "3599e8028df5ceea64bcae6521a151312d877d95f7beddf67179f8c62e5e23501a89b29e97b7ef36debbf34915d0212c1754e4a8a1dfa67ae80486af1b40ed42",
          "sha256": "8f01eebbcebbeffd9d006fee21d1725ad2ef8576f44230707223af38c754c977",
          "sha1": "0e86623fa52d13b195b5e66a53c6a861305a737b",
          "md5": "13ddb95992ed0ffa6f8712a80300ceb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.36.jar",
          "url": "yamtl.flexible-models-0.4.36.jar",
          "size": 49567,
          "sha512": "3599e8028df5ceea64bcae6521a151312d877d95f7beddf67179f8c62e5e23501a89b29e97b7ef36debbf34915d0212c1754e4a8a1dfa67ae80486af1b40ed42",
          "sha256": "8f01eebbcebbeffd9d006fee21d1725ad2ef8576f44230707223af38c754c977",
          "sha1": "0e86623fa52d13b195b5e66a53c6a861305a737b",
          "md5": "13ddb95992ed0ffa6f8712a80300ceb4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-0.4.36-all.jar",
          "url": "yamtl.flexible-models-0.4.36-all.jar",
          "size": 49567,
          "sha512": "aa7ccb9230aabf29d6a30489911894603613d42f3eeba768daaa333c9b304a5de4f9bde61c3107f9f834a383ff52fb2ed97f70a2682a2cf1ee976e64eb48fc17",
          "sha256": "49a04a536c5ed460499b84e76b9bf5605e7edb1a086c2d2367a25cc4d189fe7c",
          "sha1": "de0e43967c9e55ebc890fabcddb4bb5a07febd68",
          "md5": "72f51dab80788f58b68e00d89d47f052"
        }
      ]
    }
  ]
}
