{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6.jar",
          "url": "yamtl.flexible-models-1.1.6.jar",
          "size": 49601,
          "sha512": "dcc343902deadfec5b1b5247cdd1a44e2e8c5564f4050abe7658392f3a63aacef6b1fe0d24a3850daa4d2e445a3e84f6a53d8b4509808b589fd55c1eef6d1473",
          "sha256": "bfafd7aeb1e23bf9800daafafdc5442707ec889dd579b83da1dc7220d67f36fc",
          "sha1": "6e17c38d4cbfd71e2f897ac781df33d4e2a9790d",
          "md5": "a72ecaa1f7b0af66b7c8f5787e02c3da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6.jar",
          "url": "yamtl.flexible-models-1.1.6.jar",
          "size": 49601,
          "sha512": "dcc343902deadfec5b1b5247cdd1a44e2e8c5564f4050abe7658392f3a63aacef6b1fe0d24a3850daa4d2e445a3e84f6a53d8b4509808b589fd55c1eef6d1473",
          "sha256": "bfafd7aeb1e23bf9800daafafdc5442707ec889dd579b83da1dc7220d67f36fc",
          "sha1": "6e17c38d4cbfd71e2f897ac781df33d4e2a9790d",
          "md5": "a72ecaa1f7b0af66b7c8f5787e02c3da"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6-all.jar",
          "url": "yamtl.flexible-models-1.1.6-all.jar",
          "size": 49601,
          "sha512": "bc6d5081d9be9add2f19b9f484cd2fd94118db97db795356e3b34645e9bef3f753369a32b262de603aa6fd267ef97da2d7dda8c095cdea91c8bd8a4ca2a3cfef",
          "sha256": "51286584752e204fe02a5e5e903d0dea536792163c6ba9903e5ff75edd4087df",
          "sha1": "8e7126cf3a410e4e56a00c9b2f2c4257985c0005",
          "md5": "10060db5a98f1f498825dbb26e942f35"
        }
      ]
    }
  ]
}
