{
  "formatVersion": "1.1",
  "component": {
    "group": "yamtl",
    "module": "yamtl.flexible-models",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6.jar",
          "url": "yamtl.flexible-models-1.1.6.jar",
          "size": 49640,
          "sha512": "fa8fa81c395e50e088c92960d2e8ca1dec5305fb3fb468f0e6f70d7c33039420f7c06edf83943ae7ef2a8ff1b4dc54a7ddef5fe8e91749b67a6f7a9bd028bf1f",
          "sha256": "d108247cc740d1f0dd3f870c4fbba7faf88bbc80b5ff617462ed2bec8acb9512",
          "sha1": "1f1c34649fc8ff00da95699483af7767e02e60a4",
          "md5": "f3397e188257fc5586e0cfbc235ab7c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "4.0.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.34.0"
          }
        },
        {
          "group": "org.eclipse.emfatic",
          "module": "org.eclipse.emfatic.core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.common",
          "version": {
            "requires": "2.28.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.xmi",
          "version": {
            "requires": "2.35.0"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore.change",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.core",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "org.eclipse.xtend",
          "module": "org.eclipse.xtend.lib",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.sourceforge.plantuml",
          "module": "plantuml-mit",
          "version": {
            "requires": "1.2023.12"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.19"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        }
      ],
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6.jar",
          "url": "yamtl.flexible-models-1.1.6.jar",
          "size": 49640,
          "sha512": "fa8fa81c395e50e088c92960d2e8ca1dec5305fb3fb468f0e6f70d7c33039420f7c06edf83943ae7ef2a8ff1b4dc54a7ddef5fe8e91749b67a6f7a9bd028bf1f",
          "sha256": "d108247cc740d1f0dd3f870c4fbba7faf88bbc80b5ff617462ed2bec8acb9512",
          "sha1": "1f1c34649fc8ff00da95699483af7767e02e60a4",
          "md5": "f3397e188257fc5586e0cfbc235ab7c9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "yamtl.flexible-models-1.1.6-all.jar",
          "url": "yamtl.flexible-models-1.1.6-all.jar",
          "size": 49640,
          "sha512": "f3e41adbfd1a2656c45173005888cab9cb804087b262ed20967b59eaf2792d28ad612584ea6e9e2f99c0af55114f686de8584acaff98675764a47464ae237c0d",
          "sha256": "120b6c54bd0dde7c65b08690d269594f4b971e33c3f3da2d3e96d8ada13d0ddd",
          "sha1": "41de86ec1d4567397d05f28b88c1d7196ae4531c",
          "md5": "fa4f001d9fffae6ab0cbc15c2711e169"
        }
      ]
    }
  ]
}
